INSERT INTO tbTpMovimento (movcon, movcona, movent, moventa) VALUES ('Débito','Deb','Entrada', 'Ent'); 
INSERT INTO tbTpMovimento (movcon, movcona, movent, moventa) VALUES ('Crédito','Cre','Saída', 'Sai'); 
INSERT INTO tbTpConta (nome) VALUES ('Patrimonial'); 
INSERT INTO tbTpConta (nome) VALUES ('Resultados'); 
INSERT INTO tbTpConta (nome) VALUES ('Transitória'); 
INSERT INTO tbEstConta (nome) VALUES ('Titulo1'); 
INSERT INTO tbEstConta (nome) VALUES ('Titulo2'); 
INSERT INTO tbEstConta (nome) VALUES ('Titulo3'); 
INSERT INTO tbEstConta (nome) VALUES ('Titulo4'); 
INSERT INTO tbEstConta (nome) VALUES ('Conta'); 
INSERT INTO tbSitPeriodo (nome) VALUES ('Iniciado'); 
INSERT INTO tbSitPeriodo (nome) VALUES ('Aberto'); 
INSERT INTO tbSitPeriodo (nome) VALUES ('Fechado'); 
INSERT INTO tbAnos (nome, abrev) VALUES ('2016','16'); 
INSERT INTO tbAnos (nome, abrev) VALUES ('2017','17'); 
INSERT INTO tbAnos (nome, abrev) VALUES ('2018','18'); 
INSERT INTO tbAnos (nome, abrev) VALUES ('2019','19'); 
INSERT INTO tbAnos (nome, abrev) VALUES ('2020','20'); 
INSERT INTO tbAnos (nome, abrev) VALUES ('2021','21'); 
INSERT INTO tbAnos (nome, abrev) VALUES ('2022','22'); 
INSERT INTO tbAnos (nome, abrev) VALUES ('2023','23'); 
INSERT INTO tbMeses (nome, abrev) VALUES ('Janeiro','JAN'); 
INSERT INTO tbMeses (nome, abrev) VALUES ('Fevereiro','FEV'); 
INSERT INTO tbMeses (nome, abrev) VALUES ('Março', 'MAR'); 
INSERT INTO tbMeses (nome, abrev) VALUES ('Abril', 'ABR'); 
INSERT INTO tbMeses (nome, abrev) VALUES ('Maio', 'MAI'); 
INSERT INTO tbMeses (nome, abrev) VALUES ('Junho', 'JUN'); 
INSERT INTO tbMeses (nome, abrev) VALUES ('Julho', 'JUL'); 
INSERT INTO tbMeses (nome, abrev) VALUES ('Agosto', 'AGO'); 
INSERT INTO tbMeses (nome, abrev) VALUES ('Setembro', 'SET'); 
INSERT INTO tbMeses (nome, abrev) VALUES ('Outubro', 'OUT'); 
INSERT INTO tbMeses (nome, abrev) VALUES ('Novembro', 'NOV'); 
INSERT INTO tbMeses (nome, abrev) VALUES ('Dezembro', 'DEZ'); 
INSERT INTO tbTipoConta (nome) VALUES ('Equity'); 
INSERT INTO tbTipoConta (nome) VALUES ('Liability'); 
INSERT INTO tbTipoConta (nome) VALUES ('Asset'); 
INSERT INTO tbTipoConta (nome) VALUES ('Investment'); 
INSERT INTO tbTipoConta (nome) VALUES ('Loan'); 
INSERT INTO tbTipoConta (nome) VALUES ('Cash'); 
INSERT INTO tbTipoConta (nome) VALUES ('Credit Card'); 
INSERT INTO tbTipoConta (nome) VALUES ('Savings'); 
INSERT INTO tbTipoConta (nome) VALUES ('Checking'); 
INSERT INTO tbTipoConta (nome) VALUES ('Encerrada');     
INSERT INTO tbSitLanc (nome, abrev) VALUES ('Pendente','PE'); 
INSERT INTO tbSitLanc (nome, abrev) VALUES ('Pago','PA'); 
INSERT INTO tbSitLanc (nome, abrev) VALUES ('Em Liberação','AG'); 
INSERT INTO tbSitLanc (nome, abrev) VALUES ('Liberado','LI'); 
INSERT INTO tbSitLanc (nome, abrev) VALUES ('Lançada','LA'); 
INSERT INTO tbSitLanc (nome, abrev) VALUES ('Prevista','PR'); 
INSERT INTO tbSitLanc (nome, abrev) VALUES ('Gasto Fixo','GF'); 
